package Excecao.personalizadaA;

public class TesteValidacoes {

	public static void main(String[] args) {

		Aluno aluno;
		try {
			aluno = new Aluno("Ana", -7);
			Validar.usuario(aluno);
		} catch (StringVaziaException e) {
			// TODO Auto-generated catch block
			System.out.println(e.getMessage());
		}catch (NumeroForaIntervaloException e) {
			// TODO: handle exception
		}

		System.out.println("FIM");
		
		
	}
}
